### ISSUE TITLE
Pull requests from other repositories won't work

### ISSUE THREAD

**Issue by justinabrahms** [justinabrahms/imhotep#11]
Trying to run imhotep against #10 breaks because scottjab's PR sha isn't accessible from the main repo.

**Comment by gordol** [comment]
Is anyone else still having problems with this?

```
fatal: could not read Username for 'https://github.com': No such device or address
error: could not fetch remote
fatal: remote already exists
fatal: could not read Username for 'https://github.com': No such device or address
error: could not fetch remote
fatal: reference is not a tree xxxxxxxxxxxxxxxxxxxxx
```

Can this thing not pull private repos or something?

**Comment by gordol** [comment]
https://github.com/justinabrahms/imhotep/commit/13d0dfd957c1159c7fe6377637b10996ef91afcd

I think this is the issue...

Should we add some code to try both? If one fails, try the other? Or check if it's a private repo, and try ssh?

I'm happy to tackle this (am doing this in my local fork now)

**Comment by gordol** [comment]
Well this may be for naught...

Github seems to reject comments on PR for third party repositories for some weird reason, even if the user has admin access to said repository.

So literally I guess there's just no point in even trying to support this, then.
