### ISSUE TITLE
hasattr(self.response_format) results in TypeError

### ISSUE THREAD

**Issue by richtier** [justinabrahms/imhotep#76]
There is an error in`imhotep/tools.py` for version 0.4.0 installed via `pip` that results in `TypeError`:

```js
    if not hasattr(self.response_format):
    # TypeError: hasattr expected 2 arguments, got 1
```

The error is [here](https://github.com/justinabrahms/imhotep/blob/master/imhotep/tools.py#L67)

The fix appears to be to change the source to `hasattr(self, 'response_format')` but the fact no-one has raised this since the code was introduced ~4 months ago makes me a bit suspicious that something odd is happening.

**Comment by justinabrahms** [comment]
This is really interesting. That should certainly be as you described. Looking at the tests, there should be more coverage on that function as well, as it appears I'm completely mocking it out.

As for why this currently works, it looks like the tools aren't using that code. Some of the tools directly override `invoke` which would skip it. Others are overriding the `process_line` method which skips it.

Thanks so much for finding this. Please include your name in the CONTRIBUTORS file with the PR. :smile_cat:

**Comment by richtier** [comment]
[PR is up](https://github.com/justinabrahms/imhotep/pull/77/files)

**Comment by richtier** [comment]
PR 77 fixes issue 76. So close to parity!
