### ISSUE TITLE
Reporting file-level linter violations

### ISSUE THREAD

**Issue by danpalmer** [justinabrahms/imhotep#85]
Currently Imhotep only reports linter violations for lines that have changed. This limits useful file-level linter violations from being reported. 

I propose that Imhotep be changed to always report violations on line 0, flake8 uses this to indicate a violation at the file level. 

As lines should always be numbered from 1, this overloading of the value 0 should not cause compatibility issues, while allowing some existing linting tools to work without modification.

I'm happy to implement this, and will probably do so tomorrow, please let me know before then if this feature would not be accepted, or if the specific implementation I've proposed would not be accepted. If you have any recommendations for better implementations I would love to hear them.

**Comment by justinabrahms** [comment]
One of the driving forces in Imhotep is that it's forwards compatible. You
should be able to introduce this in a code base that doesn't implement pep8
at all, and it should slowly report errors as you change code, not all at
once.

As long as this isn't spammy, I'd be happy to take the contribution, likely
behind a cli flag. :)

 -justin

On Friday, March 25, 2016, Dan Palmer <notifications@github.com> wrote:

> Currently Imhotep only reports linter violations for lines that have
> changed. This limits useful file-level linter violations from being
> reported.
>
> I propose that Imhotep be changed to always report violations on line 0,
> flake8 uses this to indicate a violation at the file level.
>
> As lines should always be numbered from 1, this overloading of the value 0
> should not cause compatibility issues, while allowing some existing linting
> tools to work without modification.
>
> I'm happy to implement this, and will probably do so tomorrow, please let
> me know before then if this feature would not be accepted, or if the
> specific implementation I've proposed would not be accepted. If you have
> any recommendations for better implementations I would love to hear them.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/justinabrahms/imhotep/issues/85>
>


-- 
Sent via mobile phone.

**Comment by danpalmer** [comment]
This was added in https://github.com/justinabrahms/imhotep/pull/87.
