### ISSUE TITLE
New PyPI release

### ISSUE THREAD

**Issue by danpalmer** [justinabrahms/imhotep#97]
Hi @justinabrahms.

I've just changed the supported Python versions (to drop 2.6 and add 3.5/3.6, I hope that's not too bold). I've also restructured the travis build matrix to support that, and merged an outstanding bugfix PR that I had where the tests had been failing due to the Python build issues.

I believe master should be in a shippable state now with the bugfix. Could you do a PyPI release when you have a chance? I believe this should be 1.1.1, and have updated the changelog.

**Comment by justinabrahms** [comment]
Hey Dan. Would you mind writing this up in release notes for the `README.md`?

**Comment by danpalmer** [comment]
Already done, it was only the bug fix hence the 1.1.1 version bump.

**Comment by justinabrahms** [comment]
Wouldn't a drop in support for 2.6 necessitate a version bump higher than patch? I'm fine with it (ever forward progress and all that), but would prefer to not be surprising to people upgrading. I think this becomes imhotep 2.0?

**Comment by danpalmer** [comment]
Oh yes, sorry! Definitely worth a larger version bump, 2.0 sounds reasonable. Do you want to make those edits or shall I?

**Comment by justinabrahms** [comment]
Please do. I'm not actually editing any of the code in this repository due to work contracts. :-(

**Comment by danpalmer** [comment]
Oh no that's a shame. I'll do that now. Are you happy/able to push to PyPI or do you want to add me as a contributor on there?

**Comment by danpalmer** [comment]
Also, I've encountered a bug under Python 3, so it might be worth holding off on the upload until I've fixed that.

**Comment by hugovk** [comment]
How about including `classifiers` and `python_requires` in setup.py? 

For example https://github.com/pylast/pylast/blob/develop/setup.py and see https://stackoverflow.com/q/44660448/724176

**Comment by justinabrahms** [comment]
Sounds great, Hugo. Want to submit a PR?

**Comment by hugovk** [comment]
There we go! PR [💯 ](https://github.com/justinabrahms/imhotep/pull/100)
